# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/aari/Projects/Vivado/gsom/gsom.srcs/sources_1/ip/square_root/square_root.xci
# IP: The module: 'square_root' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aari/Projects/Vivado/gsom/gsom.gen/sources_1/ip/square_root/square_root_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'square_root'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/aari/Projects/Vivado/gsom/gsom.srcs/sources_1/ip/square_root/square_root.xci
# IP: The module: 'square_root' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aari/Projects/Vivado/gsom/gsom.gen/sources_1/ip/square_root/square_root_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'square_root'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
