webtalk_init -webtalk_dir /home/aari/Projects/Vivado/gsom/gsom.sim/sim_1/behav/xsim/xsim.dir/gsom_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Feb 14 17:58:45 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "31fc1e5c-146b-4da5-a61c-ca21c674ebbd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9eb27556aa5b411bac98baa750c7a52d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "369" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Pop" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Pop!_OS 21.10" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 1700 Eight-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1550.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "427180 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "933.64_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "957048_KB" -context "xsim\\usage"
webtalk_transmit -clientid 69807494 -regid "" -xml /home/aari/Projects/Vivado/gsom/gsom.sim/sim_1/behav/xsim/xsim.dir/gsom_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/aari/Projects/Vivado/gsom/gsom.sim/sim_1/behav/xsim/xsim.dir/gsom_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/aari/Projects/Vivado/gsom/gsom.sim/sim_1/behav/xsim/xsim.dir/gsom_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
