webtalk_init -webtalk_dir /home/aari/Projects/Vivado/gsom/gsom.sim/sim_1/behav/xsim/xsim.dir/gsom_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Feb 14 15:15:00 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "31fc1e5c-146b-4da5-a61c-ca21c674ebbd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9eb27556aa5b411bac98baa750c7a52d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "342" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Pop" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Pop!_OS 21.10" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 1700 Eight-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1550.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "37" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "88877 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "40999 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "1290583" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "230815" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "894.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "6847376_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3969680505 -regid "" -xml /home/aari/Projects/Vivado/gsom/gsom.sim/sim_1/behav/xsim/xsim.dir/gsom_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/aari/Projects/Vivado/gsom/gsom.sim/sim_1/behav/xsim/xsim.dir/gsom_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/aari/Projects/Vivado/gsom/gsom.sim/sim_1/behav/xsim/xsim.dir/gsom_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
